package owlcode;

public class OWLFile {
	
	String owlHead;
	
	public OWLFile() {
		owlHead = "";
		owlHead += "<?xml version=\"1.0\"?>\r\n";
		owlHead += "<Ontology xmlns=\"http://www.w3.org/2002/07/owl#\"\r\n";
		owlHead += "\t xml:base=\"http://www.semanticweb.org/felixzanetti/ontologies/2019/3/untitled-ontology-4\"\r\n";
		owlHead += "\t xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\r\n";
		owlHead += "\t xmlns:xml=\"http://www.w3.org/XML/1998/namespace\"\r\n";
		owlHead += "\t xmlns:xsd=\"http://www.w3.org/2001/XMLSchema#\"\r\n";
		owlHead += "\t xmlns:rdfs=\"http://www.w3.org/2000/01/rdf-schema#\"\r\n";
		owlHead += "\t ontologyIRI=\"http://www.semanticweb.org/felixzanetti/ontologies/2019/3/untitled-ontology-4\">\r\n";
		owlHead += "\t<Prefix name=\"\" IRI=\"http://www.semanticweb.org/felixzanetti/ontologies/2019/3/untitled-ontology-4\"/>\r\n";
		owlHead += "\t<Prefix name=\"owl\" IRI=\"http://www.w3.org/2002/07/owl#\"/>\r\n";
		owlHead += "\t<Prefix name=\"rdf\" IRI=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"/>\r\n";
		owlHead += "\t<Prefix name=\"xml\" IRI=\"http://www.w3.org/XML/1998/namespace\"/>\r\n";
		owlHead += "\t<Prefix name=\"xsd\" IRI=\"http://www.w3.org/2001/XMLSchema#\"/>\r\n";
		owlHead += "\t<Prefix name=\"rdfs\" IRI=\"http://www.w3.org/2000/01/rdf-schema#\"/>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<Class IRI=\"#OOC-O::Class\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<Class IRI=\"#OOC-O::Extendable_Class\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<Class IRI=\"#OOC-O::Inheritance\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<Class IRI=\"#OOC-O::Instance_Variable\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<Class IRI=\"#OOC-O::Member\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<Class IRI=\"#OOC-O::Member_Variable\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<Class IRI=\"#OOC-O::Primitive_Type\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<Class IRI=\"#OOC-O::Subclass\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<Class IRI=\"#OOC-O::Superclass\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<Class IRI=\"#OOC-O::Type\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<Class IRI=\"#OOC-O::Value_Type\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<Class IRI=\"#OOC-O::Variable\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Class_Mapping\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Entity_Class\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Entity_Subclass\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Entity_Superclass\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Entity_Table\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Foreign_Key_Mapping\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Inheritance_Mapping\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Many_To_Many_Relationship_Mapping\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Many_To_One_Relationship_Mapping\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Mapped_Foreign_Key\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Mapped_Primary_Key\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Mapped_Variable\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Multiple_Entity_Table\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Nullability\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::One_To_Many_Relationship_Mapping\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::One_To_One_Relationship_Mapping\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Primary_Key_Mapping\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Relationship_Association_Table\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Relationship_Mapping\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Single_Entity_Table\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Single_Table_Inheritance_Mapping\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Table_per_Class_Inheritance_Mapping\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Table_per_Concrete_Class_Inheritance_Mapping\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Variable_Mapping\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<Class IRI=\"#RDBS-O::Column\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<Class IRI=\"#RDBS-O::Column_Constraint\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<Class IRI=\"#RDBS-O::Column_Type_Constraint\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<Class IRI=\"#RDBS-O::Constraint\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<Class IRI=\"#RDBS-O::Foreign_Key_Column\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<Class IRI=\"#RDBS-O::Foreign_Key_Constraint\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<Class IRI=\"#RDBS-O::Primary_Key_Column\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<Class IRI=\"#RDBS-O::Primary_Key_Constraint\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<Class IRI=\"#RDBS-O::Table\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#entity_class_mapped_by\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#entity_class_mapped_to\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#entity_class_relationship_mapped_by\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#inherited_from\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#inherits_from\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#is_type_of\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#member_belongs_to\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#pk_mapped_by\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#pk_mapped_to\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#relationship_association_mapped_to\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#relationship_mapped_to\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#relationship_reverse_of\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#relationship_source_mapped_by\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#relationship_target_mapped_by\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#single_table_inheritance_mapped_to\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#subclass_mapped_by\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#superclass_mapped_by\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#table_per_class_inheritance_mapped_to\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#table_per_concrete_class_inheritance_mapped_to\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#variable_mapped_by\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<Declaration>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#variable_mapped_to\"/>\r\n";
		owlHead += "\t</Declaration>\r\n";
		owlHead += "\t<SubClassOf>\r\n";
		owlHead += "\t\t<Class IRI=\"#OOC-O::Class\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#OOC-O::Type\"/>\r\n";
		owlHead += "\t</SubClassOf>\r\n";
		owlHead += "\t<SubClassOf>\r\n";
		owlHead += "\t\t<Class IRI=\"#OOC-O::Extendable_Class\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#OOC-O::Class\"/>\r\n";
		owlHead += "\t</SubClassOf>\r\n";
		owlHead += "\t<SubClassOf>\r\n";
		owlHead += "\t\t<Class IRI=\"#OOC-O::Instance_Variable\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#OOC-O::Member_Variable\"/>\r\n";
		owlHead += "\t</SubClassOf>\r\n";
		owlHead += "\t<SubClassOf>\r\n";
		owlHead += "\t\t<Class IRI=\"#OOC-O::Member_Variable\"/>\r\n";
		owlHead += "\t\t<ObjectIntersectionOf>\r\n";
		owlHead += "\t\t\t<Class IRI=\"#OOC-O::Member\"/>\r\n";
		owlHead += "\t\t\t<Class IRI=\"#OOC-O::Variable\"/>\r\n";
		owlHead += "\t\t</ObjectIntersectionOf>\r\n";
		owlHead += "\t</SubClassOf>\r\n";
		owlHead += "\t<SubClassOf>\r\n";
		owlHead += "\t\t<Class IRI=\"#OOC-O::Primitive_Type\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#OOC-O::Type\"/>\r\n";
		owlHead += "\t</SubClassOf>\r\n";
		owlHead += "\t<SubClassOf>\r\n";
		owlHead += "\t\t<Class IRI=\"#OOC-O::Subclass\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#OOC-O::Class\"/>\r\n";
		owlHead += "\t</SubClassOf>\r\n";
		owlHead += "\t<SubClassOf>\r\n";
		owlHead += "\t\t<Class IRI=\"#OOC-O::Superclass\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#OOC-O::Extendable_Class\"/>\r\n";
		owlHead += "\t</SubClassOf>\r\n";
		owlHead += "\t<SubClassOf>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Entity_Class\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#OOC-O::Class\"/>\r\n";
		owlHead += "\t</SubClassOf>\r\n";
		owlHead += "\t<SubClassOf>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Entity_Subclass\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#OOC-O::Subclass\"/>\r\n";
		owlHead += "\t</SubClassOf>\r\n";
		owlHead += "\t<SubClassOf>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Entity_Superclass\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#OOC-O::Superclass\"/>\r\n";
		owlHead += "\t</SubClassOf>\r\n";
		owlHead += "\t<SubClassOf>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Entity_Table\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#RDBS-O::Table\"/>\r\n";
		owlHead += "\t</SubClassOf>\r\n";
		owlHead += "\t<SubClassOf>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Foreign_Key_Mapping\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Variable_Mapping\"/>\r\n";
		owlHead += "\t</SubClassOf>\r\n";
		owlHead += "\t<SubClassOf>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Many_To_Many_Relationship_Mapping\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Relationship_Mapping\"/>\r\n";
		owlHead += "\t</SubClassOf>\r\n";
		owlHead += "\t<SubClassOf>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Many_To_One_Relationship_Mapping\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Relationship_Mapping\"/>\r\n";
		owlHead += "\t</SubClassOf>\r\n";
		owlHead += "\t<SubClassOf>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Mapped_Foreign_Key\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Mapped_Variable\"/>\r\n";
		owlHead += "\t</SubClassOf>\r\n";
		owlHead += "\t<SubClassOf>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Mapped_Primary_Key\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Mapped_Variable\"/>\r\n";
		owlHead += "\t</SubClassOf>\r\n";
		owlHead += "\t<SubClassOf>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Mapped_Variable\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#OOC-O::Instance_Variable\"/>\r\n";
		owlHead += "\t</SubClassOf>\r\n";
		owlHead += "\t<SubClassOf>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Multiple_Entity_Table\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Entity_Table\"/>\r\n";
		owlHead += "\t</SubClassOf>\r\n";
		owlHead += "\t<SubClassOf>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::One_To_Many_Relationship_Mapping\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Relationship_Mapping\"/>\r\n";
		owlHead += "\t</SubClassOf>\r\n";
		owlHead += "\t<SubClassOf>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::One_To_One_Relationship_Mapping\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Relationship_Mapping\"/>\r\n";
		owlHead += "\t</SubClassOf>\r\n";
		owlHead += "\t<SubClassOf>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Primary_Key_Mapping\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Variable_Mapping\"/>\r\n";
		owlHead += "\t</SubClassOf>\r\n";
		owlHead += "\t<SubClassOf>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Relationship_Association_Table\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#RDBS-O::Table\"/>\r\n";
		owlHead += "\t</SubClassOf>\r\n";
		owlHead += "\t<SubClassOf>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Single_Entity_Table\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Entity_Table\"/>\r\n";
		owlHead += "\t</SubClassOf>\r\n";
		owlHead += "\t<SubClassOf>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Single_Table_Inheritance_Mapping\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Inheritance_Mapping\"/>\r\n";
		owlHead += "\t</SubClassOf>\r\n";
		owlHead += "\t<SubClassOf>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Table_per_Class_Inheritance_Mapping\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Inheritance_Mapping\"/>\r\n";
		owlHead += "\t</SubClassOf>\r\n";
		owlHead += "\t<SubClassOf>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Table_per_Concrete_Class_Inheritance_Mapping\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Inheritance_Mapping\"/>\r\n";
		owlHead += "\t</SubClassOf>\r\n";
		owlHead += "\t<SubClassOf>\r\n";
		owlHead += "\t\t<Class IRI=\"#RDBS-O::Column_Constraint\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#RDBS-O::Constraint\"/>\r\n";
		owlHead += "\t</SubClassOf>\r\n";
		owlHead += "\t<SubClassOf>\r\n";
		owlHead += "\t\t<Class IRI=\"#RDBS-O::Column_Type_Constraint\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#RDBS-O::Column_Constraint\"/>\r\n";
		owlHead += "\t</SubClassOf>\r\n";
		owlHead += "\t<SubClassOf>\r\n";
		owlHead += "\t\t<Class IRI=\"#RDBS-O::Foreign_Key_Column\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#RDBS-O::Column\"/>\r\n";
		owlHead += "\t</SubClassOf>\r\n";
		owlHead += "\t<SubClassOf>\r\n";
		owlHead += "\t\t<Class IRI=\"#RDBS-O::Foreign_Key_Constraint\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#RDBS-O::Column_Constraint\"/>\r\n";
		owlHead += "\t</SubClassOf>\r\n";
		owlHead += "\t<SubClassOf>\r\n";
		owlHead += "\t\t<Class IRI=\"#RDBS-O::Primary_Key_Column\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#RDBS-O::Column\"/>\r\n";
		owlHead += "\t</SubClassOf>\r\n";
		owlHead += "\t<SubClassOf>\r\n";
		owlHead += "\t\t<Class IRI=\"#RDBS-O::Primary_Key_Constraint\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#RDBS-O::Column_Constraint\"/>\r\n";
		owlHead += "\t</SubClassOf>\r\n";
		owlHead += "\t<ObjectPropertyDomain>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#entity_class_mapped_by\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Entity_Class\"/>\r\n";
		owlHead += "\t</ObjectPropertyDomain>\r\n";
		owlHead += "\t<ObjectPropertyDomain>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#entity_class_mapped_to\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Class_Mapping\"/>\r\n";
		owlHead += "\t</ObjectPropertyDomain>\r\n";
		owlHead += "\t<ObjectPropertyDomain>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#entity_class_relationship_mapped_by\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Entity_Class\"/>\r\n";
		owlHead += "\t</ObjectPropertyDomain>\r\n";
		owlHead += "\t<ObjectPropertyDomain>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#inherited_from\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#OOC-O::Superclass\"/>\r\n";
		owlHead += "\t</ObjectPropertyDomain>\r\n";
		owlHead += "\t<ObjectPropertyDomain>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#inherits_from\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#OOC-O::Subclass\"/>\r\n";
		owlHead += "\t</ObjectPropertyDomain>\r\n";
		owlHead += "\t<ObjectPropertyDomain>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#is_type_of\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#OOC-O::Variable\"/>\r\n";
		owlHead += "\t</ObjectPropertyDomain>\r\n";
		owlHead += "\t<ObjectPropertyDomain>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#member_belongs_to\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#OOC-O::Member\"/>\r\n";
		owlHead += "\t</ObjectPropertyDomain>\r\n";
		owlHead += "\t<ObjectPropertyDomain>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#pk_mapped_by\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Mapped_Primary_Key\"/>\r\n";
		owlHead += "\t</ObjectPropertyDomain>\r\n";
		owlHead += "\t<ObjectPropertyDomain>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#pk_mapped_to\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Primary_Key_Mapping\"/>\r\n";
		owlHead += "\t</ObjectPropertyDomain>\r\n";
		owlHead += "\t<ObjectPropertyDomain>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#relationship_association_mapped_to\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Many_To_Many_Relationship_Mapping\"/>\r\n";
		owlHead += "\t</ObjectPropertyDomain>\r\n";
		owlHead += "\t<ObjectPropertyDomain>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#relationship_mapped_to\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Relationship_Mapping\"/>\r\n";
		owlHead += "\t</ObjectPropertyDomain>\r\n";
		owlHead += "\t<ObjectPropertyDomain>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#relationship_reverse_of\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Relationship_Mapping\"/>\r\n";
		owlHead += "\t</ObjectPropertyDomain>\r\n";
		owlHead += "\t<ObjectPropertyDomain>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#relationship_source_mapped_by\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Entity_Class\"/>\r\n";
		owlHead += "\t</ObjectPropertyDomain>\r\n";
		owlHead += "\t<ObjectPropertyDomain>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#relationship_target_mapped_by\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Entity_Class\"/>\r\n";
		owlHead += "\t</ObjectPropertyDomain>\r\n";
		owlHead += "\t<ObjectPropertyDomain>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#single_table_inheritance_mapped_to\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Single_Table_Inheritance_Mapping\"/>\r\n";
		owlHead += "\t</ObjectPropertyDomain>\r\n";
		owlHead += "\t<ObjectPropertyDomain>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#subclass_mapped_by\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Entity_Subclass\"/>\r\n";
		owlHead += "\t</ObjectPropertyDomain>\r\n";
		owlHead += "\t<ObjectPropertyDomain>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#superclass_mapped_by\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Entity_Superclass\"/>\r\n";
		owlHead += "\t</ObjectPropertyDomain>\r\n";
		owlHead += "\t<ObjectPropertyDomain>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#table_per_class_inheritance_mapped_to\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Table_per_Class_Inheritance_Mapping\"/>\r\n";
		owlHead += "\t</ObjectPropertyDomain>\r\n";
		owlHead += "\t<ObjectPropertyDomain>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#table_per_concrete_class_inheritance_mapped_to\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Table_per_Concrete_Class_Inheritance_Mapping\"/>\r\n";
		owlHead += "\t</ObjectPropertyDomain>\r\n";
		owlHead += "\t<ObjectPropertyDomain>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#variable_mapped_by\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Mapped_Variable\"/>\r\n";
		owlHead += "\t</ObjectPropertyDomain>\r\n";
		owlHead += "\t<ObjectPropertyDomain>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#variable_mapped_to\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Variable_Mapping\"/>\r\n";
		owlHead += "\t</ObjectPropertyDomain>\r\n";
		owlHead += "\t<ObjectPropertyRange>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#entity_class_mapped_by\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Class_Mapping\"/>\r\n";
		owlHead += "\t</ObjectPropertyRange>\r\n";
		owlHead += "\t<ObjectPropertyRange>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#entity_class_mapped_to\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Entity_Table\"/>\r\n";
		owlHead += "\t</ObjectPropertyRange>\r\n";
		owlHead += "\t<ObjectPropertyRange>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#entity_class_relationship_mapped_by\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Relationship_Mapping\"/>\r\n";
		owlHead += "\t</ObjectPropertyRange>\r\n";
		owlHead += "\t<ObjectPropertyRange>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#inherited_from\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#OOC-O::Inheritance\"/>\r\n";
		owlHead += "\t</ObjectPropertyRange>\r\n";
		owlHead += "\t<ObjectPropertyRange>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#inherits_from\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#OOC-O::Inheritance\"/>\r\n";
		owlHead += "\t</ObjectPropertyRange>\r\n";
		owlHead += "\t<ObjectPropertyRange>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#is_type_of\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#OOC-O::Value_Type\"/>\r\n";
		owlHead += "\t</ObjectPropertyRange>\r\n";
		owlHead += "\t<ObjectPropertyRange>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#member_belongs_to\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#OOC-O::Class\"/>\r\n";
		owlHead += "\t</ObjectPropertyRange>\r\n";
		owlHead += "\t<ObjectPropertyRange>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#pk_mapped_by\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Primary_Key_Mapping\"/>\r\n";
		owlHead += "\t</ObjectPropertyRange>\r\n";
		owlHead += "\t<ObjectPropertyRange>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#pk_mapped_to\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#RDBS-O::Primary_Key_Column\"/>\r\n";
		owlHead += "\t</ObjectPropertyRange>\r\n";
		owlHead += "\t<ObjectPropertyRange>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#relationship_association_mapped_to\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Relationship_Association_Table\"/>\r\n";
		owlHead += "\t</ObjectPropertyRange>\r\n";
		owlHead += "\t<ObjectPropertyRange>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#relationship_mapped_to\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Entity_Table\"/>\r\n";
		owlHead += "\t</ObjectPropertyRange>\r\n";
		owlHead += "\t<ObjectPropertyRange>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#relationship_reverse_of\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Relationship_Mapping\"/>\r\n";
		owlHead += "\t</ObjectPropertyRange>\r\n";
		owlHead += "\t<ObjectPropertyRange>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#relationship_source_mapped_by\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Relationship_Mapping\"/>\r\n";
		owlHead += "\t</ObjectPropertyRange>\r\n";
		owlHead += "\t<ObjectPropertyRange>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#relationship_target_mapped_by\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Relationship_Mapping\"/>\r\n";
		owlHead += "\t</ObjectPropertyRange>\r\n";
		owlHead += "\t<ObjectPropertyRange>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#single_table_inheritance_mapped_to\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Multiple_Entity_Table\"/>\r\n";
		owlHead += "\t</ObjectPropertyRange>\r\n";
		owlHead += "\t<ObjectPropertyRange>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#subclass_mapped_by\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Inheritance_Mapping\"/>\r\n";
		owlHead += "\t</ObjectPropertyRange>\r\n";
		owlHead += "\t<ObjectPropertyRange>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#superclass_mapped_by\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Inheritance_Mapping\"/>\r\n";
		owlHead += "\t</ObjectPropertyRange>\r\n";
		owlHead += "\t<ObjectPropertyRange>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#table_per_class_inheritance_mapped_to\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Single_Entity_Table\"/>\r\n";
		owlHead += "\t</ObjectPropertyRange>\r\n";
		owlHead += "\t<ObjectPropertyRange>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#table_per_concrete_class_inheritance_mapped_to\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Single_Entity_Table\"/>\r\n";
		owlHead += "\t</ObjectPropertyRange>\r\n";
		owlHead += "\t<ObjectPropertyRange>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#variable_mapped_by\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#ORMF-O::Variable_Mapping\"/>\r\n";
		owlHead += "\t</ObjectPropertyRange>\r\n";
		owlHead += "\t<ObjectPropertyRange>\r\n";
		owlHead += "\t\t<ObjectProperty IRI=\"#variable_mapped_to\"/>\r\n";
		owlHead += "\t\t<Class IRI=\"#RDBS-O::Column\"/>\r\n";
		owlHead += "\t</ObjectPropertyRange>\r\n";
//		owlHead += "</Ontology>\r\n";
//		owlHead += "\r\n";
//		owlHead += "\r\n";
//		owlHead += "\r\n";
//		owlHead += "<!-- Generated by the OWL API (version 4.5.9.2019-02-01T07:24:44Z) https://github.com/owlcs/owlapi -->\r\n";
//		owlHead += "\r\n";

	}
	
	
	public String getOwlHead() {
		return owlHead;
	}
	
	public String getOwlClosure() {
		String ret = "";
		ret += "</Ontology>\n";
		ret += "<!-- Generated by the ORMFConverter https://github.com/feluzan/ORMFConverter -->\n";
		return ret;
	}


	

}
