package owlcode;

public class OWLFile {
	
	String owlHead;
	
	public OWLFile() {
		owlHead = "";
		owlHead += "<?xml version=\"1.0\"?>\n";
		owlHead += "<Ontology xmlns=\"http://www.w3.org/2002/07/owl#\"\n";
		owlHead += "     xml:base=\"http://www.semanticweb.org/felixzanetti/ontologies/2019/3/untitled-ontology-4\"\n";
		owlHead += "     xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n";
		owlHead += "	     xmlns:xml=\"http://www.w3.org/XML/1998/namespace\"\n";
		owlHead += "     xmlns:xsd=\"http://www.w3.org/2001/XMLSchema#\"\n";
		owlHead += "    xmlns:rdfs=\"http://www.w3.org/2000/01/rdf-schema#\"\n";
		owlHead += "   ontologyIRI=\"http://www.semanticweb.org/felixzanetti/ontologies/2019/3/untitled-ontology-4\">\n";
		owlHead += "    <Prefix name=\"\" IRI=\"http://www.semanticweb.org/felixzanetti/ontologies/2019/3/untitled-ontology-4\"/>\n";
		owlHead += "    <Prefix name=\"owl\" IRI=\"http://www.w3.org/2002/07/owl#\"/>\n";
		owlHead += "    <Prefix name=\"rdf\" IRI=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"/>\n";
		owlHead += "    <Prefix name=\"xml\" IRI=\"http://www.w3.org/XML/1998/namespace\"/>\n";
		owlHead += "    <Prefix name=\"xsd\" IRI=\"http://www.w3.org/2001/XMLSchema#\"/>\n";
		owlHead += "    <Prefix name=\"rdfs\" IRI=\"http://www.w3.org/2000/01/rdf-schema#\"/>\n";
		owlHead += "    <Declaration>\n";
		owlHead += "        <Class IRI=\"#OOC-O::Class\"/>\n";
		owlHead += "    </Declaration>\n";
		owlHead += "    <Declaration>\n";
		owlHead += "        <Class IRI=\"#OOC-O::Extendable_Class\"/>\n";
		owlHead += "    </Declaration>\n";
		owlHead += "    <Declaration>\n";
		owlHead += "        <Class IRI=\"#OOC-O::Instance_Variable\"/>\n";
		owlHead += "    </Declaration>\n";
		owlHead += "    <Declaration>\n";
		owlHead += "        <Class IRI=\"#OOC-O::Member\"/>\n";
		owlHead += "    </Declaration>\n";
		owlHead += "    <Declaration>\n";
		owlHead += "        <Class IRI=\"#OOC-O::Member_Variable\"/>\n";
		owlHead += "    </Declaration>\n";
		owlHead += "    <Declaration>\n";
		owlHead += "        <Class IRI=\"#OOC-O::Subclass\"/>\n";
		owlHead += "    </Declaration>\n";
		owlHead += "    <Declaration>\n";
		owlHead += "        <Class IRI=\"#OOC-O::Superclass\"/>\n";
		owlHead += "    </Declaration>\n";
		owlHead += "    <Declaration>\n";
		owlHead += "        <Class IRI=\"#OOC-O::Variable\"/>\n";
		owlHead += "    </Declaration>\n";
		owlHead += "    <Declaration>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Class_Mapping\"/>\n";
		owlHead += "    </Declaration>\n";
		owlHead += "    <Declaration>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Entity_Class\"/>\n";
		owlHead += "    </Declaration>\n";
		owlHead += "    <Declaration>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Entity_Subclass\"/>\n";
		owlHead += "    </Declaration>\n";
		owlHead += "    <Declaration>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Entity_Superclass\"/>\n";
		owlHead += "    </Declaration>\n";
		owlHead += "    <Declaration>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Entity_Table\"/>\n";
		owlHead += "    </Declaration>\n";
		owlHead += "    <Declaration>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Foreign_Key_Mapping\"/>\n";
		owlHead += "    </Declaration>\n";
		owlHead += "    <Declaration>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Inheritance_Mapping\"/>\n";
		owlHead += "    </Declaration>\n";
		owlHead += "    <Declaration>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Many_To_Many_Relationship_Mapping\"/>\n";
		owlHead += "    </Declaration>\n";
		owlHead += "    <Declaration>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Many_To_One_Relationship_Mapping\"/>\n";
		owlHead += "    </Declaration>\n";
		owlHead += "    <Declaration>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Mapped_Foreign_Key\"/>\n";
		owlHead += "    </Declaration>\n";
		owlHead += "    <Declaration>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Mapped_Primary_Key\"/>\n";
		owlHead += "    </Declaration>\n";
		owlHead += "    <Declaration>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Mapped_Variable\"/>\n";
		owlHead += "    </Declaration>\n";
		owlHead += "    <Declaration>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Multiple_Entity_Table\"/>\n";
		owlHead += "    </Declaration>\n";
		owlHead += "    <Declaration>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Nullability\"/>\n";
		owlHead += "    </Declaration>\n";
		owlHead += "    <Declaration>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::One_To_Many_Relationship_Mapping\"/>\n";
		owlHead += "    </Declaration>\n";
		owlHead += "    <Declaration>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::One_To_One_Relationship_Mapping\"/>\n";
		owlHead += "    </Declaration>\n";
		owlHead += "    <Declaration>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Primary_Key_Mapping\"/>\n";
		owlHead += "    </Declaration>\n";
		owlHead += "    <Declaration>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Relationship_Association_Table\"/>\n";
		owlHead += "    </Declaration>\n";
		owlHead += "    <Declaration>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Relationship_Mapping\"/>\n";
		owlHead += "    </Declaration>\n";
		owlHead += "    <Declaration>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Single_Entity_Table\"/>\n";
		owlHead += "    </Declaration>\n";
		owlHead += "    <Declaration>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Single_Table_Inheritance_Mapping\"/>\n";
		owlHead += "    </Declaration>\n";
		owlHead += "    <Declaration>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Table_per_Class_Inheritance_Mapping\"/>\n";
		owlHead += "    </Declaration>\n";
		owlHead += "    <Declaration>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Table_per_Concrete_Class_Inheritance_Mapping\"/>\n";
		owlHead += "    </Declaration>\n";
		owlHead += "    <Declaration>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Variable_Mapping\"/>\n";
		owlHead += "    </Declaration>\n";
		owlHead += "    <Declaration>\n";
		owlHead += "        <Class IRI=\"#RDBS-O::Column\"/>\n";
		owlHead += "    </Declaration>\n";
		owlHead += "    <Declaration>\n";
		owlHead += "        <Class IRI=\"#RDBS-O::Column_Constraint\"/>\n";
		owlHead += "    </Declaration>\n";
		owlHead += "    <Declaration>\n";
		owlHead += "        <Class IRI=\"#RDBS-O::Column_Type_Constraint\"/>\n";
		owlHead += "    </Declaration>\n";
		owlHead += "    <Declaration>\n";
		owlHead += "        <Class IRI=\"#RDBS-O::Constraint\"/>\n";
		owlHead += "    </Declaration>\n";
		owlHead += "    <Declaration>\n";
		owlHead += "        <Class IRI=\"#RDBS-O::Foreign_Key_Column\"/>\n";
		owlHead += "    </Declaration>\n";
		owlHead += "    <Declaration>\n";
		owlHead += "        <Class IRI=\"#RDBS-O::Foreign_Key_Constraint\"/>\n";
		owlHead += "    </Declaration>\n";
		owlHead += "    <Declaration>\n";
		owlHead += "        <Class IRI=\"#RDBS-O::Primary_Key_Column\"/>\n";
		owlHead += "    </Declaration>\n";
		owlHead += "    <Declaration>\n";
		owlHead += "        <Class IRI=\"#RDBS-O::Primary_Key_Constraint\"/>\n";
		owlHead += "    </Declaration>\n";
		owlHead += "    <Declaration>\n";
		owlHead += "        <Class IRI=\"#RDBS-O::Table\"/>\n";
		owlHead += "    </Declaration>\n";
		owlHead += "    <Declaration>\n";
		owlHead += "        <ObjectProperty IRI=\"#entity_class_mapped_by\"/>\n";
		owlHead += "    </Declaration>\n";
		owlHead += "    <Declaration>\n";
		owlHead += "        <ObjectProperty IRI=\"#entity_class_mapped_to\"/>\n";
		owlHead += "    </Declaration>\n";
		owlHead += "    <Declaration>\n";
		owlHead += "        <ObjectProperty IRI=\"#entity_class_relationship_mapped_by\"/>\n";
		owlHead += "    </Declaration>\n";
		owlHead += "    <Declaration>\n";
		owlHead += "        <ObjectProperty IRI=\"#member_belongs_to\"/>\n";
		owlHead += "    </Declaration>\n";
		owlHead += "    <Declaration>\n";
		owlHead += "        <ObjectProperty IRI=\"#pk_mapped_by\"/>\n";
		owlHead += "    </Declaration>\n";
		owlHead += "    <Declaration>\n";
		owlHead += "        <ObjectProperty IRI=\"#pk_mapped_to\"/>\n";
		owlHead += "    </Declaration>\n";
		owlHead += "    <Declaration>\n";
		owlHead += "        <ObjectProperty IRI=\"#relationship_association_mapped_to\"/>\n";
		owlHead += "    </Declaration>\n";
		owlHead += "    <Declaration>\n";
		owlHead += "        <ObjectProperty IRI=\"#relationship_mapped_by\"/>\n";
		owlHead += "    </Declaration>\n";
		owlHead += "    <Declaration>\n";
		owlHead += "        <ObjectProperty IRI=\"#relationship_mapped_to\"/>\n";
		owlHead += "    </Declaration>\n";
		owlHead += "    <Declaration>\n";
		owlHead += "        <ObjectProperty IRI=\"#single_table_inheritance_mapped_to\"/>\n";
		owlHead += "    </Declaration>\n";
		owlHead += "    <Declaration>\n";
		owlHead += "        <ObjectProperty IRI=\"#subclass_mapped_by\"/>\n";
		owlHead += "    </Declaration>\n";
		owlHead += "    <Declaration>\n";
		owlHead += "        <ObjectProperty IRI=\"#superclass_mapped_by\"/>\n";
		owlHead += "    </Declaration>\n";
		owlHead += "    <Declaration>\n";
		owlHead += "        <ObjectProperty IRI=\"#table_per_class_inheritance_mapped_to\"/>\n";
		owlHead += "    </Declaration>\n";
		owlHead += "    <Declaration>\n";
		owlHead += "        <ObjectProperty IRI=\"#table_per_concrete_class_inheritance_mapped_to\"/>\n";
		owlHead += "    </Declaration>\n";
		owlHead += "    <Declaration>\n";
		owlHead += "        <ObjectProperty IRI=\"#variable_mapped_by\"/>\n";
		owlHead += "    </Declaration>\n";
		owlHead += "    <Declaration>\n";
		owlHead += "        <ObjectProperty IRI=\"#variable_mapped_to\"/>\n";
		owlHead += "    </Declaration>\n";
		owlHead += "    <SubClassOf>\n";
		owlHead += "        <Class IRI=\"#OOC-O::Extendable_Class\"/>\n";
		owlHead += "        <Class IRI=\"#OOC-O::Class\"/>\n";
		owlHead += "    </SubClassOf>\n";
		owlHead += "    <SubClassOf>\n";
		owlHead += "        <Class IRI=\"#OOC-O::Instance_Variable\"/>\n";
		owlHead += "        <Class IRI=\"#OOC-O::Member_Variable\"/>\n";
		owlHead += "    </SubClassOf>\n";
		owlHead += "    <SubClassOf>\n";
		owlHead += "        <Class IRI=\"#OOC-O::Member_Variable\"/>\n";
		owlHead += "        <ObjectIntersectionOf>\n";
		owlHead += "            <Class IRI=\"#OOC-O::Member\"/>\n";
		owlHead += "            <Class IRI=\"#OOC-O::Variable\"/>\n";
		owlHead += "        </ObjectIntersectionOf>\n";
		owlHead += "    </SubClassOf>\n";
		owlHead += "    <SubClassOf>\n";
		owlHead += "        <Class IRI=\"#OOC-O::Subclass\"/>\n";
		owlHead += "        <Class IRI=\"#OOC-O::Class\"/>\n";
		owlHead += "    </SubClassOf>\n";
		owlHead += "    <SubClassOf>\n";
		owlHead += "        <Class IRI=\"#OOC-O::Superclass\"/>\n";
		owlHead += "        <Class IRI=\"#OOC-O::Extendable_Class\"/>\n";
		owlHead += "    </SubClassOf>\n";
		owlHead += "    <SubClassOf>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Entity_Class\"/>\n";
		owlHead += "        <Class IRI=\"#OOC-O::Class\"/>\n";
		owlHead += "    </SubClassOf>\n";
		owlHead += "    <SubClassOf>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Entity_Subclass\"/>\n";
		owlHead += "        <Class IRI=\"#OOC-O::Subclass\"/>\n";
		owlHead += "    </SubClassOf>\n";
		owlHead += "    <SubClassOf>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Entity_Superclass\"/>\n";
		owlHead += "        <Class IRI=\"#OOC-O::Superclass\"/>\n";
		owlHead += "    </SubClassOf>\n";
		owlHead += "    <SubClassOf>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Entity_Table\"/>\n";
		owlHead += "        <Class IRI=\"#RDBS-O::Table\"/>\n";
		owlHead += "    </SubClassOf>\n";
		owlHead += "    <SubClassOf>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Foreign_Key_Mapping\"/>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Variable_Mapping\"/>\n";
		owlHead += "    </SubClassOf>\n";
		owlHead += "    <SubClassOf>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Many_To_Many_Relationship_Mapping\"/>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Relationship_Mapping\"/>\n";
		owlHead += "    </SubClassOf>\n";
		owlHead += "    <SubClassOf>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Many_To_One_Relationship_Mapping\"/>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Relationship_Mapping\"/>\n";
		owlHead += "    </SubClassOf>\n";
		owlHead += "    <SubClassOf>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Mapped_Foreign_Key\"/>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Mapped_Variable\"/>\n";
		owlHead += "    </SubClassOf>\n";
		owlHead += "    <SubClassOf>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Mapped_Primary_Key\"/>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Mapped_Variable\"/>\n";
		owlHead += "    </SubClassOf>\n";
		owlHead += "    <SubClassOf>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Mapped_Variable\"/>\n";
		owlHead += "        <Class IRI=\"#OOC-O::Instance_Variable\"/>\n";
		owlHead += "    </SubClassOf>\n";
		owlHead += "    <SubClassOf>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Multiple_Entity_Table\"/>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Entity_Table\"/>\n";
		owlHead += "    </SubClassOf>\n";
		owlHead += "    <SubClassOf>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::One_To_Many_Relationship_Mapping\"/>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Relationship_Mapping\"/>\n";
		owlHead += "    </SubClassOf>\n";
		owlHead += "    <SubClassOf>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::One_To_One_Relationship_Mapping\"/>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Relationship_Mapping\"/>\n";
		owlHead += "    </SubClassOf>\n";
		owlHead += "    <SubClassOf>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Primary_Key_Mapping\"/>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Variable_Mapping\"/>\n";
		owlHead += "    </SubClassOf>\n";
		owlHead += "    <SubClassOf>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Relationship_Association_Table\"/>\n";
		owlHead += "        <Class IRI=\"#RDBS-O::Table\"/>\n";
		owlHead += "    </SubClassOf>\n";
		owlHead += "    <SubClassOf>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Single_Entity_Table\"/>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Entity_Table\"/>\n";
		owlHead += "    </SubClassOf>\n";
		owlHead += "    <SubClassOf>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Single_Table_Inheritance_Mapping\"/>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Inheritance_Mapping\"/>\n";
		owlHead += "    </SubClassOf>\n";
		owlHead += "    <SubClassOf>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Table_per_Class_Inheritance_Mapping\"/>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Inheritance_Mapping\"/>\n";
		owlHead += "    </SubClassOf>\n";
		owlHead += "    <SubClassOf>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Table_per_Concrete_Class_Inheritance_Mapping\"/>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Inheritance_Mapping\"/>\n";
		owlHead += "    </SubClassOf>\n";
		owlHead += "    <SubClassOf>\n";
		owlHead += "        <Class IRI=\"#RDBS-O::Column_Constraint\"/>\n";
		owlHead += "        <Class IRI=\"#RDBS-O::Constraint\"/>\n";
		owlHead += "    </SubClassOf>\n";
		owlHead += "    <SubClassOf>\n";
		owlHead += "        <Class IRI=\"#RDBS-O::Column_Type_Constraint\"/>\n";
		owlHead += "        <Class IRI=\"#RDBS-O::Column_Constraint\"/>\n";
		owlHead += "    </SubClassOf>\n";
		owlHead += "    <SubClassOf>\n";
		owlHead += "        <Class IRI=\"#RDBS-O::Foreign_Key_Column\"/>\n";
		owlHead += "        <Class IRI=\"#RDBS-O::Column\"/>\n";
		owlHead += "    </SubClassOf>\n";
		owlHead += "    <SubClassOf>\n";
		owlHead += "        <Class IRI=\"#RDBS-O::Foreign_Key_Constraint\"/>\n";
		owlHead += "        <Class IRI=\"#RDBS-O::Column_Constraint\"/>\n";
		owlHead += "    </SubClassOf>\n";
		owlHead += "    <SubClassOf>\n";
		owlHead += "        <Class IRI=\"#RDBS-O::Primary_Key_Column\"/>\n";
		owlHead += "        <Class IRI=\"#RDBS-O::Column\"/>\n";
		owlHead += "    </SubClassOf>\n";
		owlHead += "    <SubClassOf>\n";
		owlHead += "        <Class IRI=\"#RDBS-O::Primary_Key_Constraint\"/>\n";
		owlHead += "        <Class IRI=\"#RDBS-O::Column_Constraint\"/>\n";
		owlHead += "    </SubClassOf>\n";
		owlHead += "    <ObjectPropertyDomain>\n";
		owlHead += "        <ObjectProperty IRI=\"#entity_class_mapped_by\"/>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Entity_Class\"/>\n";
		owlHead += "    </ObjectPropertyDomain>\n";
		owlHead += "    <ObjectPropertyDomain>\n";
		owlHead += "        <ObjectProperty IRI=\"#entity_class_mapped_to\"/>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Class_Mapping\"/>\n";
		owlHead += "    </ObjectPropertyDomain>\n";
		owlHead += "    <ObjectPropertyDomain>\n";
		owlHead += "        <ObjectProperty IRI=\"#entity_class_relationship_mapped_by\"/>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Entity_Class\"/>\n";
		owlHead += "    </ObjectPropertyDomain>\n";
		owlHead += "    <ObjectPropertyDomain>\n";
		owlHead += "        <ObjectProperty IRI=\"#member_belongs_to\"/>\n";
		owlHead += "        <Class IRI=\"#OOC-O::Member\"/>\n";
		owlHead += "    </ObjectPropertyDomain>\n";
		owlHead += "    <ObjectPropertyDomain>\n";
		owlHead += "        <ObjectProperty IRI=\"#pk_mapped_by\"/>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Mapped_Primary_Key\"/>\n";
		owlHead += "    </ObjectPropertyDomain>\n";
		owlHead += "    <ObjectPropertyDomain>\n";
		owlHead += "        <ObjectProperty IRI=\"#pk_mapped_to\"/>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Primary_Key_Mapping\"/>\n";
		owlHead += "    </ObjectPropertyDomain>\n";
		owlHead += "    <ObjectPropertyDomain>\n";
		owlHead += "        <ObjectProperty IRI=\"#relationship_association_mapped_to\"/>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Many_To_Many_Relationship_Mapping\"/>\n";
		owlHead += "    </ObjectPropertyDomain>\n";
		owlHead += "    <ObjectPropertyDomain>\n";
		owlHead += "        <ObjectProperty IRI=\"#relationship_mapped_by\"/>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Entity_Class\"/>\n";
		owlHead += "    </ObjectPropertyDomain>\n";
		owlHead += "    <ObjectPropertyDomain>\n";
		owlHead += "        <ObjectProperty IRI=\"#relationship_mapped_to\"/>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Relationship_Mapping\"/>\n";
		owlHead += "    </ObjectPropertyDomain>\n";
		owlHead += "    <ObjectPropertyDomain>\n";
		owlHead += "        <ObjectProperty IRI=\"#single_table_inheritance_mapped_to\"/>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Single_Table_Inheritance_Mapping\"/>\n";
		owlHead += "    </ObjectPropertyDomain>\n";
		owlHead += "    <ObjectPropertyDomain>\n";
		owlHead += "        <ObjectProperty IRI=\"#subclass_mapped_by\"/>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Entity_Subclass\"/>\n";
		owlHead += "    </ObjectPropertyDomain>\n";
		owlHead += "    <ObjectPropertyDomain>\n";
		owlHead += "        <ObjectProperty IRI=\"#superclass_mapped_by\"/>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Entity_Superclass\"/>\n";
		owlHead += "    </ObjectPropertyDomain>\n";
		owlHead += "    <ObjectPropertyDomain>\n";
		owlHead += "        <ObjectProperty IRI=\"#table_per_class_inheritance_mapped_to\"/>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Table_per_Class_Inheritance_Mapping\"/>\n";
		owlHead += "    </ObjectPropertyDomain>\n";
		owlHead += "    <ObjectPropertyDomain>\n";
		owlHead += "        <ObjectProperty IRI=\"#table_per_concrete_class_inheritance_mapped_to\"/>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Table_per_Concrete_Class_Inheritance_Mapping\"/>\n";
		owlHead += "    </ObjectPropertyDomain>\n";
		owlHead += "    <ObjectPropertyDomain>\n";
		owlHead += "        <ObjectProperty IRI=\"#variable_mapped_by\"/>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Mapped_Variable\"/>\n";
		owlHead += "    </ObjectPropertyDomain>\n";
		owlHead += "    <ObjectPropertyDomain>\n";
		owlHead += "        <ObjectProperty IRI=\"#variable_mapped_to\"/>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Variable_Mapping\"/>\n";
		owlHead += "    </ObjectPropertyDomain>\n";
		owlHead += "    <ObjectPropertyRange>\n";
		owlHead += "        <ObjectProperty IRI=\"#entity_class_mapped_by\"/>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Class_Mapping\"/>\n";
		owlHead += "    </ObjectPropertyRange>\n";
		owlHead += "    <ObjectPropertyRange>\n";
		owlHead += "        <ObjectProperty IRI=\"#entity_class_mapped_to\"/>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Entity_Table\"/>\n";
		owlHead += "    </ObjectPropertyRange>\n";
		owlHead += "    <ObjectPropertyRange>\n";
		owlHead += "        <ObjectProperty IRI=\"#entity_class_relationship_mapped_by\"/>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Relationship_Mapping\"/>\n";
		owlHead += "    </ObjectPropertyRange>\n";
		owlHead += "    <ObjectPropertyRange>\n";
		owlHead += "        <ObjectProperty IRI=\"#member_belongs_to\"/>\n";
		owlHead += "        <Class IRI=\"#OOC-O::Class\"/>\n";
		owlHead += "    </ObjectPropertyRange>\n";
		owlHead += "    <ObjectPropertyRange>\n";
		owlHead += "        <ObjectProperty IRI=\"#pk_mapped_by\"/>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Primary_Key_Mapping\"/>\n";
		owlHead += "    </ObjectPropertyRange>\n";
		owlHead += "    <ObjectPropertyRange>\n";
		owlHead += "        <ObjectProperty IRI=\"#pk_mapped_to\"/>\n";
		owlHead += "        <Class IRI=\"#RDBS-O::Primary_Key_Column\"/>\n";
		owlHead += "    </ObjectPropertyRange>\n";
		owlHead += "    <ObjectPropertyRange>\n";
		owlHead += "        <ObjectProperty IRI=\"#relationship_association_mapped_to\"/>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Relationship_Association_Table\"/>\n";
		owlHead += "    </ObjectPropertyRange>\n";
		owlHead += "    <ObjectPropertyRange>\n";
		owlHead += "        <ObjectProperty IRI=\"#relationship_mapped_by\"/>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Relationship_Mapping\"/>\n";
		owlHead += "    </ObjectPropertyRange>\n";
		owlHead += "    <ObjectPropertyRange>\n";
		owlHead += "        <ObjectProperty IRI=\"#relationship_mapped_to\"/>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Entity_Table\"/>\n";
		owlHead += "    </ObjectPropertyRange>\n";
		owlHead += "    <ObjectPropertyRange>\n";
		owlHead += "        <ObjectProperty IRI=\"#single_table_inheritance_mapped_to\"/>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Multiple_Entity_Table\"/>\n";
		owlHead += "    </ObjectPropertyRange>\n";
		owlHead += "    <ObjectPropertyRange>\n";
		owlHead += "        <ObjectProperty IRI=\"#subclass_mapped_by\"/>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Inheritance_Mapping\"/>\n";
		owlHead += "    </ObjectPropertyRange>\n";
		owlHead += "    <ObjectPropertyRange>\n";
		owlHead += "        <ObjectProperty IRI=\"#superclass_mapped_by\"/>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Inheritance_Mapping\"/>\n";
		owlHead += "    </ObjectPropertyRange>\n";
		owlHead += "    <ObjectPropertyRange>\n";
		owlHead += "        <ObjectProperty IRI=\"#table_per_class_inheritance_mapped_to\"/>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Single_Entity_Table\"/>\n";
		owlHead += "    </ObjectPropertyRange>\n";
		owlHead += "    <ObjectPropertyRange>\n";
		owlHead += "        <ObjectProperty IRI=\"#table_per_concrete_class_inheritance_mapped_to\"/>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Single_Entity_Table\"/>\n";
		owlHead += "    </ObjectPropertyRange>\n";
		owlHead += "    <ObjectPropertyRange>\n";
		owlHead += "        <ObjectProperty IRI=\"#variable_mapped_by\"/>\n";
		owlHead += "        <Class IRI=\"#ORMF-O::Variable_Mapping\"/>\n";
		owlHead += "    </ObjectPropertyRange>\n";
		owlHead += "    <ObjectPropertyRange>\n";
		owlHead += "        <ObjectProperty IRI=\"#variable_mapped_to\"/>\n";
		owlHead += "        <Class IRI=\"#RDBS-O::Column\"/>\n";
		owlHead += "    </ObjectPropertyRange>\n";
	}
	
	
	public String getOwlHead() {
		return owlHead;
	}
	
	public String getOwlClosure() {
		String ret = "";
		ret += "</Ontology>\n";
		ret += "<!-- Generated by the ORMFConverter https://github.com/feluzan/ORMFConverter -->\n";
		return ret;
	}


	

}
